[server]
headless = true
port = 8501
baseUrlPath = "/"
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[runner]
fastReruns = true
mainScriptPath = "app/app.py"

[client]
showErrorDetails = true

[theme]
base = "light"

[logger]
level = "debug"
